Run npm run build:installer
  
> osu-link@1.0.3-dev.1 build:installer
> node scripts/resolve-and-sync-version.mjs && node scripts/tauri-build-with-signing.mjs
[resolve-version] Syncing app version to 1.0.3-dev.2
v1.0.3-dev.2
Synced Tauri/Cargo version to 1.0.3-dev.2
(node:10104) [DEP0190] DeprecationWarning: Passing args to a child process with shell option true can lead to security vulnerabilities, as the arguments are not escaped, only concatenated.
(Use `node --trace-deprecation ...` to show where the warning was created)
[tauri-build] CI: TAURI_SIGNING_PRIVATE_KEY set (348 chars)
Using TAURI_SIGNING_PRIVATE_KEY from environment.
        Info Looking up installed tauri packages to check mismatched versions...
     Running beforeBuildCommand `npm run build`
> osu-link@1.0.3-dev.2 build
> tsc && vite build
vite v7.3.2 building client environment for production...
transforming...
✓ 695 modules transformed.
rendering chunks...
computing gzip size...
dist/index.html                                                       0.47 kB │ gzip:   0.30 kB
dist/assets/plus-jakarta-sans-vietnamese-400-normal-Cg2kxhWu.woff2    4.10 kB
dist/assets/plus-jakarta-sans-vietnamese-800-normal-CxbopLd3.woff2    4.14 kB
dist/assets/plus-jakarta-sans-vietnamese-600-normal-Y4VTTRme.woff2    4.20 kB
dist/assets/plus-jakarta-sans-vietnamese-700-normal-CV6qDkkj.woff2    4.27 kB
dist/assets/plus-jakarta-sans-vietnamese-500-normal-DiU8zqi-.woff2    4.28 kB
dist/assets/plus-jakarta-sans-vietnamese-400-normal-B8TCSmUq.woff     5.60 kB
dist/assets/plus-jakarta-sans-vietnamese-800-normal-BkoGl_sr.woff     5.69 kB
dist/assets/plus-jakarta-sans-vietnamese-600-normal-5YsyKbU1.woff     5.74 kB
dist/assets/plus-jakarta-sans-vietnamese-700-normal-BCh_uG_5.woff     5.78 kB
dist/assets/plus-jakarta-sans-vietnamese-500-normal-CvE5C8T-.woff     5.79 kB
dist/assets/plus-jakarta-sans-latin-ext-400-normal-D127hM_v.woff2    10.59 kB
dist/assets/plus-jakarta-sans-latin-ext-800-normal-B6BjB2Ju.woff2    10.80 kB
dist/assets/plus-jakarta-sans-latin-ext-500-normal-9VZagAe1.woff2    10.86 kB
dist/assets/plus-jakarta-sans-latin-ext-600-normal-DQgPU_Cg.woff2    10.90 kB
dist/assets/plus-jakarta-sans-latin-ext-700-normal-BajbvANd.woff2    11.01 kB
dist/assets/plus-jakarta-sans-latin-400-normal-Dhut76fR.woff2        11.82 kB
dist/assets/plus-jakarta-sans-latin-800-normal-CusIZhrK.woff2        11.90 kB
dist/assets/plus-jakarta-sans-latin-600-normal-DLTa1BUW.woff2        12.19 kB
dist/assets/plus-jakarta-sans-latin-700-normal-CfpNZvy6.woff2        12.24 kB
dist/assets/plus-jakarta-sans-latin-500-normal-Bf-nb4oT.woff2        12.31 kB
dist/assets/plus-jakarta-sans-latin-ext-400-normal-2ppkqaOR.woff     15.31 kB
dist/assets/plus-jakarta-sans-latin-ext-800-normal-BPkb-LBK.woff     15.41 kB
dist/assets/plus-jakarta-sans-latin-ext-600-normal-B0WRRYJ1.woff     15.61 kB
dist/assets/plus-jakarta-sans-latin-ext-700-normal-8-d-IyIQ.woff     15.62 kB
dist/assets/plus-jakarta-sans-latin-ext-500-normal-CqEEAICU.woff     15.62 kB
dist/assets/plus-jakarta-sans-latin-400-normal-BDKaGhyp.woff         15.73 kB
dist/assets/plus-jakarta-sans-latin-800-normal-BRNHt2w0.woff         15.78 kB
dist/assets/plus-jakarta-sans-latin-600-normal-BR_Ojra4.woff         16.08 kB
dist/assets/plus-jakarta-sans-latin-500-normal-DYtqi0QS.woff         16.12 kB
dist/assets/plus-jakarta-sans-latin-700-normal-DqEcQeE5.woff         16.14 kB

(!) Some chunks are larger than 500 kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
dist/assets/index-OC1pYJvm.css                                      107.16 kB │ gzip:  26.67 kB
dist/assets/index-DuCNr8cP.js                                       843.64 kB │ gzip: 235.19 kB
✓ built in 3.43s
    Updating crates.io index
   Compiling osu-link v1.0.3-dev.2 (D:\a\osu-link\osu-link\src-tauri)
    Finished `release` profile [optimized] target(s) in 1m 49s
       Built application at: D:\a\osu-link\osu-link\src-tauri\target\release\osu-link.exe
        Info Patching D:\a\osu-link\osu-link\src-tauri\target\release\osu-link.exe with bundle type information: msi
        Info Verifying wix package
 Downloading https://github.com/wixtoolset/wix3/releases/download/wix3141rtm/wix314-binaries.zip
        Info validating hash
        Info extracting WIX
failed to bundle project `optional pre-release identifier in app version must be numeric-only and cannot be greater than 65535 for msi target`
       Error failed to bundle project `optional pre-release identifier in app version must be numeric-only and cannot be greater than 65535 for msi target`
Error: Process completed with exit code 1.
